Create a github issue templete with a link to RI2
oneclick/rubyinstaller pull request #372
Opened 2017-07-30 12:27 UTC by larskanis

Hopefully this will lead bug reports to the correct repository.

2017-08-04 19:48 UTC, luislavena requested changes

2017-08-04 19:48 UTC, luislavena commented on .github/ISSUE_TEMPLATE.md
> +This project is for Ruby version 2.3 and older.
I would emphasize this with `**NOTE**`, `**IMPORTANT**` or similar.

2017-08-04 20:35 UTC, larskanis commented on .github/ISSUE_TEMPLATE.md
> +This project is for Ruby version 2.3 and older.
I'll change this. However the markdown syntax is interpreted not before the issue is posted.

2017-08-05 03:01 UTC, luislavena approved these changes
LGTM

2017-08-08 11:12 UTC, merged

2017-08-08 11:18 UTC, larskanis commented
@luislavena Thank you for your feedback! Maybe you're interested in the [proposed changes to rubyinstaller.org](https://github.com/oneclick/rubyinstaller.org-website/pull/3) as well?